/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 flamingo.gltf 
Author: smeerws (https://sketchfab.com/smeerws)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medium-flamingo-8b18013265524e108b4e5c22a131dd6b
Title: Medium | Flamingo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/flamingo.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.023, -0.008, -0.21]} rotation={[1.905, -0.977, 0]} scale={0.4}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Layer_1__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_2__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_3__0.geometry} material={materials['Scene_-_Root']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/flamingo.gltf')
